coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
codecov:
  notify:
    after_n_builds: 3
