repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
    exclude: meta.yaml
  - id: trailing-whitespace
    exclude: pgmpy/estimators/ScoreCache.py
  - id: end-of-file-fixer
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--config=.flake8]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--profile=black]
    exclude: pgmpy/estimators/ScoreCache.py
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
