#!/usr/bin/env python3
#
# pgmpy documentation build configuration file, created by
# sphinx-quickstart on Tue Aug 30 18:17:42 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys
from pathlib import Path

TUTORIALS_PATH_ENV_VAR = "PGMPY_TUTORIALS_PATH"
VERSIONS_FILE_ENV_VAR = "PGMPY_DOCS_VERSIONS_FILE"

sys.path.insert(0, os.path.abspath("_ext"))
sys.path.insert(0, os.path.abspath("../"))

tutorials_path = os.environ.get(TUTORIALS_PATH_ENV_VAR, os.path.abspath("../../pgmpy_tutorials/notebooks"))
if os.path.isdir(tutorials_path):
    sys.path.insert(0, os.path.abspath(tutorials_path))

import pgmpy_docs

versions_manifest_path = Path(os.environ.get(VERSIONS_FILE_ENV_VAR, Path(__file__).with_name("versions.json")))
versions_manifest = pgmpy_docs.load_versions_manifest(versions_manifest_path)
site_config = pgmpy_docs.resolve_site_config(manifest=versions_manifest)
versions_payload = pgmpy_docs.build_versions_payload(versions_manifest, site_root_url=site_config.site_root_url)

# -- General configuration ------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.autosummary",
    "sphinx.ext.autosectionlabel",
    "numpydoc",
    "myst_parser",
    "nbsphinx",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinxext.opengraph",
    "sphinx_sitemap",
    "pgmpy_docs",
]

templates_path = ["_templates"]
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "myst",
}
root_doc = "index"
master_doc = root_doc

project = "pgmpy"
copyright = "2025, pgmpy developers"
author = "Ankur Ankan, Abinash Panda"

version = site_config.version_name
release = site_config.release
language = "en"

exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]
nbsphinx_execute = "never"
pygments_style = "tango"
todo_include_todos = True

myst_enable_extensions = ["colon_fence", "deflist", "fieldlist"]
myst_heading_anchors = 3
autosummary_generate = True
autosummary_generate_overwrite = True

# -- Options for HTML output ----------------------------------------------

html_theme = "pydata_sphinx_theme"

html_title = "pgmpy"
html_favicon = "logo_favi.ico"
html_logo = "_static/images/logo.png"
html_static_path = ["_static"]
html_extra_path = ["robots.txt"]
html_sidebars = {
    "**": ["sidebar-nav-bs.html"],
    "index": [],
}

html_theme_options = {
    "logo": {
        "text": "pgmpy",
    },
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["versioning.html", "theme-switcher", "navbar-icon-links"],
    "navbar_persistent": ["search-button-field"],
    "header_links_before_dropdown": 4,
    "collapse_navigation": True,
    "navigation_depth": 4,
    "show_nav_level": 1,
    "show_toc_level": 2,
    "secondary_sidebar_items": {
        "**": ["page-toc"],
        "index": [],
    },
    "primary_sidebar_end": ["pgmpy-ethical-ads"],
    "footer_start": ["copyright"],
    "footer_center": [],
    "footer_end": [],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/pgmpy/pgmpy",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/DRkdKaumBs",
            "icon": "fa-brands fa-discord",
        },
        {
            "name": "LinkedIn",
            "url": "https://www.linkedin.com/company/pgmpy/",
            "icon": "fa-brands fa-linkedin",
        },
    ],
}

html_context = {
    "pgmpy_site_root_url": site_config.site_root_url,
    "pgmpy_version_name": site_config.version_name,
    "pgmpy_versions": versions_payload,
    "pgmpy_current_version_label": pgmpy_docs.current_version_label(site_config),
}

html_css_files = ["custom.css"]

html_search_language = "en"
htmlhelp_basename = "pgmpydoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(root_doc, "pgmpy.tex", "pgmpy Documentation", "Ankur Ankan", "manual")]

# -- Options for manual page output ---------------------------------------

man_pages = [(root_doc, "pgmpy", "pgmpy Documentation", [author], 1)]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (
        root_doc,
        "pgmpy",
        "pgmpy Documentation",
        author,
        "pgmpy",
        "Python Library for Causal and Probabilistic Modeling using Bayesian Networks.",
        "Miscellaneous",
    )
]

# To suppress autosummary warnings while building docs.
numpydoc_show_class_members = False

# -- SEO configuration -----------------------------------------------------

# Base URL for sitemap and canonical links
html_baseurl = f"{site_config.base_url.rstrip('/')}/"
site_url = html_baseurl
sitemap_url_scheme = "{link}"
sitemap_locales = [None]

# Open Graph metadata (social sharing previews)
ogp_site_url = html_baseurl
ogp_site_name = site_config.site_name
ogp_image = site_config.social_image
ogp_description_length = 200
ogp_type = "website"
ogp_custom_meta_tags = [
    '<meta name="twitter:card" content="summary_large_image" />',
]
