name: pgmpy
on: [push, pull_request]
jobs:
  test:
    name: Running tests - OS - ${{ matrix.os }}; Python - ${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        group: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Print python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest-split
          python -m pip install .[all,tests] --no-cache-dir
      - name: Print package versions
        run: |
          python -m pip freeze
      - name: Run tests
        run: python -m pytest --cov-config .coveragerc --cov-report html --cov-report term --cov=pgmpy --splits 3 --group ${{ matrix.group }} --verbose --junitxml=test-results.xml || true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          files: test-results.xml
