name: pgmpy CI

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: "Tests - OS: ${{ matrix.os }}; Python: ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        group: [1, 2, 3]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Print Python info
        run: |
          which python
          python --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade black
          pip install pytest-split
          pip install .[all,tests] --no-cache-dir

      - name: Check Black formatting
        run: |
          black --diff .
          black --check .

      - name: Run Flake8 linting
        run: |
          pip install flake8
          flake8 pgmpy --config=.flake8

      - name: Print package versions
        run: |
          pip freeze

      - name: Run tests
        run: |
          pytest --cov-config=.coveragerc \
                 --cov-report=html \
                 --cov-report=term \
                 --cov=pgmpy \
                 --splits=3 \
                 --group=${{ matrix.group }} \
                 --verbose \
                 --junitxml=test-results.xml || true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          files: test-results.xml
