name: Linting Checks

on: [pull_request, merge_group]

jobs:
  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v5

      - name: python environment step
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install graphviz graphviz-dev -y

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install .[all,tests]

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Print changed files
        run: |
          echo "Changed files:" && echo "$CHANGED_FILES" | tr ' ' '\n'

      - name: Run pre-commit on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            pre-commit run --color always --files $CHANGED_FILES --show-diff-on-failure
          else
            echo "No changed files to check."
          fi
